export const AVAILABILITY_ACTIONS = {
    FETCH: 'FETCH_AVAILABILITY',
    POST: 'POST_AVAILABILITY',
    STORE: 'STORE_AVAILABILITY',
    REMOVE: 'REMOVE_AVAILABILITY',
    EDIT: 'EDIT_AVAILABILITY',
}