export const CLEANING_TYPE_ACTIONS = {
        FETCH: 'FETCH_CLEANING_TYPE',
        POST: 'POST_CLEANING_TYPE',
        STORE: 'STORE_CLEANING_TYPE',
        REMOVE: 'REMOVE_CLEANING_TYPE',
        EDIT: 'EDIT_CLEANING_TYPE'
    }
