export const CUSTOMER_ACTIONS = {
    CONTACT: 'STORE_CONTACT',
    ROOMS: 'STORE_ROOMS',
    APPT: 'STORE_APPT',
    LOCATION: 'STORE_LOCATION',
    DURATION: 'STORE_ESTIMATE',
    POST: 'POST_CUSTOMER_REQUEST',
    RESET: 'RESET_CUSTOMER_REQUEST'
};